[theme]
primaryColor = "#1DB954"  # Spotify green
backgroundColor = "#121212"  # Dark background
secondaryBackgroundColor = "#282828"  # Dark gray for cards
textColor = "#FFFFFF"  # White text
font = "sans serif"
